### ISSUE TITLE
Compilation Error: cannot find -lsgx_tsgxssld and -lsgx_tsgxssl_cryptod

### ISSUE THREAD

**Issue by zzylol** [MonashCybersecurityLab/measurement#1]
Dear Authors,

I installed openssl 1.1.1 (SGXSSL is needed) from https://github.com/intel/intel-sgx-ssl. This gives `libsgx_tsgxssl.a` and `libsgx_tsgxssl_crypto.a` in `opt/intel/sgxssl/lib64`.

But during compilation with HW mode, it needs to find `libsgx_tsgxssld.a(so)` and the same for crypto library as below:
`/usr/local/bin/ld: cannot find -lsgx_tsgxssld
/usr/local/bin/ld: cannot find -lsgx_tsgxssl_cryptod`

Could you describe more on how to install SGXSSL?

Thanks!

**Comment by shangqi-lai** [comment]
Hi,

Could you please check whether your SGXSSL is installed in the correct path?

In the [makefile](https://github.com/MonashCybersecurityLab/measurement/blob/master/Oblivious/Enclave/Makefile) of my project, you should be able to find the setting for the OpenSSL installation path:

`OPENSSL_LIBRARY_PATH ?= /opt/intel/sgxssl/lib64`.

Please let me know if you still have any issues with compilation.

Shangqi

**Comment by shangqi-lai** [comment]
I am wondering if you have solved this issue.

**Comment by shangqi-lai** [comment]
I would close this issue since there is no more comments
